export const CHANGELOG = [
  {
    version: "v1.28",
    date: "26 Jul 2026",
    title: "Security Hardening, Code Audit & RizenCC Separation",
    highlights: [
      "Full code review remediation: 82 findings resolved across auth, API, and frontend",
      "Auth hardened: rate limiting on all endpoints, 12+ char password policy enforced everywhere, 2FA re-auth requirement",
      "Secrets at rest encrypted with AES-256-GCM (TOTP seeds, AI API keys) with lazy legacy migration",
      "SSRF guard blocks all private/internal IPs including IPv6 — AI provider fetches routed through guard",
      "Cross-tenant authorization enforced — heroes can only access their own tracking and batch data",
      "XSS eliminated in Three.js labels and effect dependencies — all user text escaped",
      "Navigation resume, skip-all, concurrency, and slow-arrival edge cases hardened",
      "22 regression tests added for secrets, SSRF, rate limiter, navigation state, XSS",
      "OSRM/VROOM bound to loopback with resource limits and healthy healthchecks",
      "Database REINDEX fixed index corruption; production restored from pre-promotion backup",
      "Daily backup cron (18:00 UTC) with integrity verification",
      "Production promoted: dev merged to sidekick.rizen.space — HTTPS 200, all routes verified",
      "Corrected HERO Sidekick v1.27 APK delivered (package space.rizen.sidekick)",
      "RizenCC separated into standalone repo (package com.rizencc) — no longer embedded in Sidekick",
      "Light/dark map toggle on all pages with localStorage persistence",
      "CSP + HSTS security headers configured",
    ],
    changes: [
      "Rate limiting on login, register, check-2fa, 2fa-setup, 2fa-verify endpoints",
      "Password policy upgraded to 12+ chars on register, users routes, and user update",
      "2FA setup now requires password re-auth + current TOTP when already enabled",
      "Secrets encrypted with AES-256-GCM via src/lib/secrets.ts with backwards-compat migration",
      "SSRF guard in src/lib/url-guard.ts + src/lib/ai-fetch.ts; IPv6 [::1] blocked",
      "Tile prefetch validates bbox, zoom, and map capability",
      "Cross-tenant authz: track/complete, batch/status, verify-address/batch all constrained by userId",
      "Three.js labels escaped via escapeHtml(); TubeGeometry immutable; overlays as separate BufferGeometry",
      "Navigation: absolute index converted to upcoming index; skip-all no longer persists COMPLETED",
      "Tracking/planner polling serialized with seq + abort guard; routeReqId generation guard",
      "Slow-arrival accuracyOk guard applied to slow branch in use-navigation-engine",
      "CSP + HSTS in next.config.ts; PM2 binds 127.0.0.1; Nginx hardened (timeouts, body cap)",
      "Tile proxy API supports ?style=light for CARTO light_all tiles",
      "Backgrounds adapt to selected style on all map surfaces",
      "Navigation map switches tile source via MapLibre setStyle()",
    ],
  },
  {
    version: "v1.27",
    date: "24 Jul 2026",
    title: "Smart Drop-Point Selection & Route Editor",
    highlights: [
      "Route optimizer now picks the shortest drop-off point per load — compares DROP_A (Cyberjaya) vs DROP_B (PJ) from your last pickup and chooses the shorter route",
      "Distance target indicator: total distance shown in green (≤100 km) or amber (>100 km) with alternative-drop comparison",
      "Tap 'switch to …' on any load to toggle its drop point and see the difference live",
      "Drag-and-drop reorder: grab the ⋮⋮ grip handle to rearrange pickup stops — ETAs and distances recalculate instantly",
      "Reverse route button (⇅) on each load flips the stop order so you can test whether the opposite direction is shorter",
    ],
    changes: [
      "Saved routes from before this update are auto-upgraded — no data loss",
    ],
  },
  {
    version: "v1.26",
    date: "Jul 2026",
    title: "Android: Pull-to-Refresh Fix & Settings Changelog",
    highlights: [
      "Android: Pull-to-refresh disabled on route optimizer / map pages — dragging the map no longer reloads",
      "Android: Added AndroidBridge.openSettings() and setPullToRefresh() JS bridges",
      "Android: App version now dynamic in Settings (reads BuildConfig.VERSION_NAME)",
      "Android: Settings page now has What's New changelog section at the bottom",
      "Android: User-agent strings auto-update with version number",
    ],
    changes: [],
  },
  {
    version: "v1.25",
    date: "Jul 2026",
    title: "Android: GPS Crash Fixed",
    highlights: [
      "CRITICAL: Fixed crash loop where enabling GPS then relaunching would crash immediately",
      "Root cause: startForegroundService called without location permission check — Android 14 throws SecurityException",
      "Added safeStartGpsTracking() with permission check + try/catch at all 4 call sites",
      "Fixed onResume auto-restart crash — GPS pref now resets to false when permission missing",
    ],
    changes: [],
  },
  {
    version: "v1.24",
    date: "Jul 2026",
    title: "Android: Source Audit & Rebuild",
    highlights: [
      "Full source audit: all layouts, drawables, colors, IDs, permissions verified present",
      "Application ID: space.rizen.sidekick, minSdk 24, targetSdk 34",
      "ProGuard/R8: -keep class space.rizen.sidekick.**",
    ],
    changes: [],
  },
  {
    version: "v1.23",
    date: "Jul 2026",
    title: "Android: Initial Sidekick Release",
    highlights: [
      "WebView-based app loading sidekick.rizen.space",
      "GPS tracking via foreground service (FusedLocationProviderClient)",
      "JavaScript bridge: startGpsTracking, stopGpsTracking, isGpsTracking, getAppVersion, showToast",
      "Settings: server URL, GPS toggle + interval, push notifications",
      "Deep link support for /track/[token] URLs",
    ],
    changes: [],
  },
  {
    version: "v1.21",
    date: "Jul 2026",
    title: "Size System Overhaul & Points Increase",
    highlights: [
      "Default order size changed from Small (1pt) to Medium (2pt) for new orders",
      "New XL (4pt) and XXL (15pt) size options — better size-to-load mapping",
      "Encore CSV import now defaults to Medium (2pt) size",
      "Size scale: S=1, M=2, L=3, XL=4, XXL=15",
      "MAX_DAILY_POINTS increased from 12 to 20 — can fit more orders per day",
      "Points validation updated to allow 1-20 points per order",
      "Skip today and tomorrow in scheduler — no more accidental same-day assignments",
    ],
    changes: [
      "getSizePoints() updated with XL and XXL cases, default changed from 1 to 2",
      "SIZE_CONFIG expanded with XL and XXL entries with purple and red color badges",
      "Form defaults: new orders start at M/2pt instead of S/1pt",
      "Size selector in order form now includes X-Large and XX-Large options",
      "Encore CSV import: imported orders now default to Medium (2pt) size",
      "MAX_DAILY_POINTS raised from 12 to 20 in zones.ts",
      "Frontend points validation: 1-20 (was 1-12), error messages updated",
      "Backend points validation: all API routes updated to allow up to 20 points",
      "UI labels and help text updated across the app to reflect new size scale",
      "Scheduler: added skip for today (i=0) and tomorrow (i=1), first working day is +2",
"Order sorting feature (v1.20): Sort by creation date, order ID, or last update",
      "Restored missing batch status/date API endpoints for bulk order operations",
    ],
  },
  {
    version: "v1.20",
    date: "Jul 2026",
    title: "Order Sorting",
    highlights: [
      "New Sort dropdown in the Orders tab — sort by creation date, order ID, or last update",
      "Stops ERTHBOX orders from always pinning to the top — sort by date/ID to reorder",
      "Default sort is 'Latest created first' (matches previous behaviour)",
    ],
    changes: [
      "Added Sort select dropdown in the Orders filter bar (next to date filter)",
      "Sort options: Latest created first, Oldest created first, Order ID ascending, Order ID descending, Latest updated first, Oldest updated first",
      "Order ID sort parses the numeric portion of the orderId (handles Encore 5-digit IDs)",
      "Sort applies after filtering — filter + sort work together",
      "Default: 'Latest created first' so existing users see no change in order",
    ],
  },
  {
    version: "v1.19",
    date: "Jul 2026",
    title: "ntfy Push Notifications — Firebase Removed",
    highlights: [
      "Push notifications now powered by self-hosted ntfy — no Google Play Services required",
      "Removed Firebase FCM entirely — no service account keys, no OAuth tokens, no API costs",
      "Android app uses real-time SSE subscription instead of FCM data messages",
      "ntfy server running on VPS at ntfy.erthsidekick.xyz with 12h message cache",
      "Works on devices without Google Play Services (Huawei, custom ROMs, degoogled phones)",
    ],
    changes: [
      "Installed ntfy v2.11.0 server on VPS (systemd service, port 2586, Caddy reverse proxy)",
      "Created src/lib/ntfy.ts — drop-in replacement for fcm.ts with identical API",
      "All notification triggers (SOS, orders, chat, daily broadcast) now publish via ntfy HTTP POST",
      "Each device generates a unique unguessable topic (sk-<32hex>) — topic name is the auth credential",
      "Android: removed Firebase BoM, firebase-messaging, google-services plugin, google-services.json",
      "Android: removed SidekickFirebaseMessagingService and FcmRegistrar entirely",
      "Android: new NtfySubscriber foreground service — subscribes via SSE long-poll, auto-reconnects",
      "Android: new NtfyRegistrar — generates topic locally, registers with server via WebView fetch",
      "Android: NtfySubscriber replaces NotificationPollService (polling fallback also removed)",
      "Android: version bumped to 1.1.0 (versionCode 2) — new APK required",
      "BootReceiver now starts NtfySubscriber instead of poll service on device boot",
      "WebView JS bridge injects __sidekickPushToken (ntfy topic) instead of __sidekickFcmToken",
      "DeviceToken table reused — ntfy topic stored as token field, platform = 'android-ntfy'",
      "ntfy Caddy block configured with 24h read/write timeout for long-lived SSE connections",
    ],
  },
  {
    version: "v1.18",
    date: "Jul 2026",
    title: "Smart Scheduler, Office Detection Fix & Backup Hardening",
    highlights: [
      "Auto-scheduler rewritten with geographic clustering — orders now grouped by proximity, not just fill-order",
      "Zone-contiguous days keep one region per trip; centroid-based scoring minimises driving distance",
      "Day-density packing fills days to capacity before opening a new one — no more single-order stranded days",
      "Office detection fixed — Pangsapuri, Kondominium, Apartment, Taman addresses no longer falsely flagged as offices",
      "Malaysian-specific residential keyword pre-filter catches condos before the AI even looks at them",
      "Encore import no longer assumes every customer name is a company — personal names now correctly classified",
      "Daily backups now archive the full app build + source code — rollback can never lose features again",
    ],
    changes: [
      "Rewrote scheduler.ts: two-phase algorithm with centroid clustering, zone-contiguous processing, Phase B rebalance",
      "Phase A: greedy min-travel assignment — computes haversine centroid per day, places nearest orders together",
      "Phase B: rebalance eliminates single-order days by merging stranded orders into nearby same-zone days",
      "Scheduler now geocodes pending orders missing coordinates before scheduling, so proximity scoring always works",
      "Office detection: isLikelyResidential() pre-filter catches 20+ Malaysian housing terms (Pangsapuri, Kondominium, etc.)",
      "Office detection: AI prompt rewritten with explicit Malaysia-specific rules — Taman = housing, NEVER office",
      "Office detection: pre-filter overrides AI result — keyword check always wins if AI misclassifies",
      "Encore import: fixed critical bug where ALL non-phone customer names were marked as offices (e.g. 'Ali bin Abu')",
      "Encore import: now uses company-name indicator list + business-hours keywords instead of blanket name assumption",
      "Encore import: residential text in address overrides company name signals (home business ≠ office pickup)",
      "Automatic AI office detection on order creation (POST /api/orders) with customerName context",
      "Fixed address verification zone type bug — suggestedZone now coerced from string to Int for Prisma",
      "Daily backup script now archives app build (56 MB standalone) + app source (756 KB) for 30-day retention",
      "Geocode Orders feature: confirmed fully removed from active UI (v1.13 removal is permanent)",
    ],
  },
  {
    version: "v1.17",
    date: "Jun 2026",
    title: "Performance: Client-Side Caching & Live Revalidation",
    highlights: [
      "Orders, stats, and holidays now load instantly from a local cache (no more blank screen on open)",
      "Background revalidation swaps in fresh data without a loading flash (stale-while-revalidate)",
      "Auto-refresh every 45s + on app-foreground, so data self-heals — no need to quit and re-enter",
      "Rapid actions (batch status, delete) coalesce into a single refetch instead of N simultaneous ones",
      "First load is the only time you see 'Loading...'; afterwards the last-known data always paints instantly",
    ],
    changes: [
      "useFetchData upgraded to a cached stale-while-revalidate hook backed by localStorage",
      "Cached data renders immediately on mount; a background fetch swaps in fresh data when it arrives",
      "isLoading is now true ONLY on the first-ever load (no cached data); revalidating flag covers background refreshes",
      "Fixed loading-flag race: isLoading/revalidating set before the fetch starts, cleared only on settle",
      "refreshAll debounced (300ms) so batch operations trigger one coalesced refetch, not N×3 simultaneous fetches",
      "Auto-revalidation interval (45s) re-fetches orders + stats, paused when the tab is hidden (battery)",
      "visibilitychange listener triggers an immediate refresh when the app returns to the foreground",
      "Eliminates the 'quit app to make data appear' issue — stale data is always shown and self-heals",
    ],
  },
  {
    version: "v1.16",
    date: "Jun 2026",
    title: "Scheduling, SOS, Notifications & Daily AI Briefing",
    highlights: [
      "Auto-scheduler no longer assigns orders to today or tomorrow (already-over / locked days)",
      "SOS accept bug fixed — heroes can now answer SOS without a false 'order already exists' error",
      "Push notifications fixed — Android app now reliably registers its FCM token via the WebView",
      "Editing an address now automatically triggers re-verification",
      "Chat drawer top bar no longer hidden behind the Android status bar",
      "AI sends a daily summary to every hero at 7am MYT with a push notification",
      "Status changes show real error messages instead of a silent 'Failed'",
    ],
    changes: [
      "Scheduler: skip today (i=0) and tomorrow (i=1) when building working days — first available day is +2",
      "SOS accept: cross-user duplicate check now excludes the original order (it's about to be transferred), fixing the false DUPLICATE_ORDER 409",
      "Android: FCM token registered via WebView same-origin fetch (was failing 401 because the native HTTP call lacked the session cookie)",
      "Android: explicit token fetch on launch via FirebaseMessaging.getToken() + re-injection on refresh",
      "Android: chat drawer SheetHeader gets safe-top padding to clear the edge-to-edge status bar",
      "Orders edit: verifyOrderAddress called after address/city change (non-blocking) so re-verification is automatic",
      "Orders edit: stale 'Points must be between 1 and 20' message corrected to use MAX_DAILY_POINTS",
      "Daily broadcast: new daily-broadcast.ts generates a personalized summary per hero + sends a push + in-app notification",
      "Daily broadcast: 60s interval scheduler triggers at 07:00 MYT daily, idempotent per day, skips heroes with no orders",
      "Daily broadcast: /api/ai/daily-summary-broadcast admin endpoint for manual testing",
      "Status change: updateStatus now surfaces the server error message and distinguishes network errors",
    ],
  },
  {
    version: "v1.15",
    date: "Jun 2026",
    title: "Android App, Push Notifications & Vision AI",
    highlights: [
      "Native Android app (HERO Sidekick) wrapping the webapp with push notifications",
      "Push notifications for SOS requests, new orders assigned, system alerts, and chat mentions",
      "AI now runs on Ollama (minimax-m3:cloud) with photo upload for vision-based questions",
      "Address verification fixed — uses geocoding + AI, no longer fails with missing-SDK error",
      "AI model picker dropdown in Settings auto-fetches available models from your provider",
      "Header redesigned: two-tier layout so login/logout never gets cut off on mobile",
    ],
    changes: [
      "Android: Kotlin WebView shell (com.erth.sidekick) with FCM push + foreground polling fallback",
      "Android: Firebase Cloud Messaging v1 API (OAuth2 JWT from service account) for reliable delivery",
      "Android: camera + gallery photo picker for AI chat file uploads",
      "Android: adaptive launcher icon from Sidekick.png, edge-to-edge viewport with safe-area insets",
      "Server: DeviceToken model + /api/devices/register endpoint for push token registration",
      "Server: FCM sender (fcm.ts) with batched fan-out + token cache invalidation on key rotation",
      "Server: push triggers wired into SOS, order reassign, system notifications, chat mentions",
      "Server: Ollama installed as local cloud proxy (127.0.0.1:11434) authenticated to ollama.com",
      "Server: address-verify rewritten to use chatWithDeepSeek (Ollama) + Nominatim, dropped z-ai-web-dev-sdk",
      "Server: /api/ai/models endpoint fetches available models from configured provider for the selector",
      "Webapp: ChatMessage supports vision content (text + image_url) for multimodal models",
      "Webapp: AI chat accepts up to 4 images, downsized to 1024px JPEG, sent to vision model",
      "Webapp: AI model picker is now a dropdown populated from the provider, with manual fallback + refresh",
      "Webapp: two-tier header (brand row + actions row) fixes login/logout cut-off on narrow screens",
      "Webapp: fixed header spacer uses calc(6rem+env(safe-area-inset-top)) to clear notch on Android",
      "Webapp: favicon + web manifest + Sidekick.png branding across header, login, and loading splash",
      "Fix: clicking the status badge no longer simultaneously opens the timeline/audit dialog",
      "Fix: same timeline-conflict bug fixed on the points (size) button — now only opens Change Points dialog",
      "Fix: points selectors (create-order + change-points) now offer 1–20 (was hardcoded 12 despite 20pt cap)",
      "Fix: AI chat context + daily-summary now reference the 20pt cap via MAX_DAILY_POINTS constant",
    ],
  },
  {
    version: "v1.14",
    date: "Jun 2026",
    title: "Mobile-First UI Redesign & Bottom Navigation",
    highlights: [
      "Mobile bottom navigation bar replaces cramped top tab strip on small screens",
      "Premium dark theme with obsidian slate palette, emerald accents, proper WCAG contrast",
      "Splash screen redesigned with animated loading telemetry bar",
      "Desktop tabs remain as sticky top strip — responsive per-viewport optimization",
      "Fixed empty scroll gaps and bottom nav persistence on mobile",
    ],
    changes: [
      "Replaced top TabsList with sticky bottom navigation bar on mobile (sm:hidden)",
      "Bottom nav: icon + label per tab, SOS badge with ping animation, 56px touch targets",
      "Desktop: tabs unchanged, hidden on mobile via hidden sm:block",
      "Main layout: overflow-y-auto on main content, bottom nav fixed to viewport (z-50)",
      "Bottom nav: safe-area-inset-bottom padding for notched devices",
      "Added pb-24 bottom padding on main content to prevent nav overlap on mobile",
      "Loading screen: centered flex layout with ShieldCheck icon, pulse animation, progress bar",
      "Header: updated to uppercase tracking-widest typography, ShieldCheck emerald branding",
      "Color palette: #0B0F17 base, #161B22 cards, #21262D borders, #34D399 emerald primary, #8B949E secondary text, #F87171 destructive",
      "Fixed bottom nav disappearing on scroll by converting main to overflow-y-auto with flex-1 parent",
      "Fixed empty scroll gap by restructuring layout to contain scrolling within main area",
    ],
  },
  {
    version: "v1.13",
    date: "Jun 2026",
    title: "Multi-Order Select, Balance Display & Address Verification",
    highlights: [
      "Admin Dashboard now shows DeepSeek account balance",
      "Multi-order selection in Orders tab — select, filter by date, and batch change status",
      "Address verification automatically triggers after Encore CSV import with progress panel",
      "Removed Geocode Orders feature and map — eliminates wrong GPS in Zeo exports",
    ],
    changes: [
      "Admin Dashboard: DeepSeek balance card displays current account credit from /api/ai/balance",
      "Orders tab: date filter input added next to zone filter for filtering by scheduled date",
      "Orders tab: Select mode toggle button allows batch selection of orders",
      "Orders tab: batch action bar appears when orders are selected — choose new status and apply",
      "Orders tab: batch PATCH /api/orders/batch/status updates selected orders in bulk (max 100)",
      "OrderCard: checkbox and highlight ring shown when select mode is active",
      "Encore CSV import now triggers AI address verification for imported orders",
      "VerificationProgressDrawer shows real-time progress of address verification",
      "Fixed: onVerifyStart callback properly threaded through NewOrderTab and SettingsTab",
      "Removed: GeocodeSection component, Geocode Orders UI in Settings, geocode changelog entries",
      "Removed: Auto-Geocoding help section from knowledge base",
      "Removed: hero-map.tsx component (map feature deleted entirely)",
      "Cleaned up v1.7 changelog section (removed auto-geocoding references)",
    ],
  },
  {
    version: "v1.12",
    date: "Jun 2026",
    title: "Zone System Overhaul & Smart Matching",
    highlights: [
      "Zone system audit — fixed 6 zone-related bugs including scheduler ignoring disabled zones",
      "Smart zone matching — prevents false matches like 'kl' matching 'klcc' with word-boundary detection",
      "Auto-scheduler now respects disabled zones — orders in disabled zones are re-detected automatically",
      "Zone filter shows enabled zones first, disabled zones separated and greyed out",
      "Zone badges on orders now visually indicate when a zone is disabled (strikethrough + 'off' label)",
      "Schema comment corrected from '1-7' to '1-14, 100+ custom zones'",
    ],
    changes: [
      "Fixed CRITICAL: Auto-scheduler ignored disabled zones — orders in disabled zones were still grouped and scheduled under them, now re-detects zone before scheduling",
      "Fixed CRITICAL: Loose zone matching — 'kl' matched 'klcc', 'pj' matched anywhere; short area codes (≤3 chars) now require exact word-boundary match",
      "Fixed: Zone filter dropdown showed all zones equally — now shows enabled zones first, disabled zones under a 'Disabled' section with reduced opacity",
      "Fixed: Custom zones that were disabled still appeared in filter — now filtered by isEnabled flag",
      "Fixed: ZoneBadge had no visual indication of disabled zones — now shows strikethrough + '(off)' label for disabled zones",
      "Fixed: OrderCard didn't pass disabled zone info — now receives disabledZones prop and passes isDisabled to ZoneBadge",
      "Updated zone matching algorithm: new zoneMatch() function with smart rules — exact match, word-boundary for short codes, substring for longer names",
      "Updated detectZoneWithCustom to use the same zoneMatch() function for consistency",
      "Updated Prisma schema comment: zone Int // 1-7 → // 1-14 built-in, 100+ custom zones",
      "Scheduler now fetches disabledZones from settings before grouping, and re-assigns orders in disabled zones to the next best zone",
    ],
  },
  {
    version: "v1.11",
    date: "Jun 2026",
    title: "Full System Audit & Performance Optimization",
    highlights: [
      "83 bugs audited across frontend, backend, and database — 40+ critical/high fixes applied",
      "Fixed 165+ JWT session errors — NEXTAUTH_SECRET now properly configured",
      "Eliminated infinite re-render loops in Chat & Notifications — major speed improvement",
      "Added 19 database indexes — 10-100x query speedup for orders, stats, and audit logs",
      "Optimized for 10+ concurrent users — WAL mode, API caching, batched writes, pagination",
      "Hardened security — status transition validation, IDOR protection, race condition fixes, prompt injection mitigation",
    ],
    changes: [
      "Fixed CRITICAL: NEXTAUTH_SECRET not set — caused 165+ JWT decryption errors and constant 401s after server restart",
      "Fixed CRITICAL: ChatBubble infinite re-render loop — lastSeenId state caused useEffect→setState→re-render cycle, replaced with useRef",
      "Fixed CRITICAL: ChatDrawer polling infinite loop — messages in useEffect deps caused interval reset on every new message",
      "Fixed CRITICAL: No order status transition validation — users could skip workflow stages or revert completed orders, now enforces PENDING→SCHEDULED→CONFIRMED→BOOKED→COMPLETED",
      "Fixed CRITICAL: SOS answer race condition — two users answering the same SOS could cause data loss, now wrapped in db.$transaction with atomic check-and-update",
      "Fixed CRITICAL: Notification IDOR — any authenticated user could create notifications for any other user, now restricted to self or ADMIN/SUPPORT only",
      "Fixed CRITICAL: Duplicate order IDs persisted with _warning flag — now returns 409 rejection for data integrity",
      "Fixed CRITICAL: AI prompt injection via address/city fields — user input now sanitized (newlines stripped, length capped)",
      "Fixed: Removed wasteful notification poll that fired every 30s and discarded the response",
      "Fixed: NotificationBell double fetch — replaced ?limit=1 then ?limit=100 with single ?limit=50 request",
      "Fixed: useFetchData swallowed errors silently — now exposes error and isLoading states; empty URLs are skipped",
      "Fixed: deleteOrder showed success toast regardless of server response — now checks res.ok first",
      "Fixed: WhatsApp template saves were fire-and-forget — now awaits and checks response before showing success",
      "Fixed: OrderCard date dialog showed stale state — newDate now resets to order.scheduledDate when dialog opens",
      "Fixed: AI action UPDATE_ORDER payload had no validation — now validates size (S/M/L), date format, name/phone/city lengths, points range",
      "Fixed: ERTHBOX delete left orphaned order references — now checks for associated orders before deletion",
      "Fixed: AI chat loaded ALL orders into memory — replaced with 8 targeted queries (pending: 20, scheduled: 20, today, thisWeek, events: 10, erthbox: 10)",
      "Fixed: Holiday seed created 23 records sequentially — now uses createMany batch insert",
      "Added 19 database indexes across 10 models: Order (6), AuditLog (3), Notification (2), ChatMessage (1), SOSRequest (2), AiMessage (1), AiAction (2), AiFlag (1), Holiday (1), OffDay (1)",
      "Enabled SQLite WAL mode — allows concurrent reads during writes, critical for multi-user support",
      "Added 5-second in-memory cache for /api/heroes — repeat requests served instantly",
      "Added 3-second per-user cache for /api/stats — dashboard loads faster on repeat visits",
      "Added pagination to /api/orders — accepts ?page=1&limit=50, returns { orders, total, page, totalPages }",
      "Batched scheduler updates with db.$transaction — single atomic transaction instead of N sequential updates",
      "Optimized generateErthboxId — uses findFirst+orderBy desc instead of fetching ALL erthbox orders",
      "Fixed TOTP backup codes using Math.random — now uses crypto.randomBytes for cryptographic security",
      "Made Prisma query logging dev-only — removed production overhead",
      "Fixed: Admin/Support dashboards didn't refresh on global refresh — added dashboardRefreshKey cache buster",
      "Fixed: Native <select> in SupportDashboard — replaced with shadcn Select for visual consistency",
      "Fixed: ErthboxLocation interface missing user field — added proper type, removed unsafe type assertions",
      "Renamed AI Settings 'Validate' button to 'Save & Validate' — accurately describes that it persists the key",
      "Consolidated Settings tab useEffect hooks from 6 to 3 using Promise.all",
      "Optimized Import Encore duplicate check — targeted IN clause instead of loading ALL system orders",
      "Added take limits to Support Stats hero order queries (200 per hero, 50 for all active)",
      "Added 400ms debounce to AuditLog search input",
      "Fixed MiniBarChart using array index as key — now uses d.date for stable React keys",
      "Wrapped ScheduleTab calendar computations in useMemo — prevents redundant recalculation on re-renders",
      "Fixed OnboardingModal step state not resetting when reopened",
      "Fixed ERTHBOX search state not cleared when toggling off ERTHBOX mode",
    ],
  },
  {
    version: "v1.10",
    date: "Jun 2026",
    title: "AI Action System Audit & Hardening",
    highlights: [
      "AI can now reschedule orders — uses [ACTION:RESCHEDULE_ORDER] blocks that require your approval",
      "Fixed AI falsely claiming 'Done ✅' without actually making changes — now always uses action blocks",
      "Fixed BOOKED order protection was completely broken — AI could modify locked orders",
      "ERTHBOX locations are now truly universal — AI can see and use all active locations, not just your own",
      "Comprehensive audit of all AI-system interaction functions — 7 bugs found and fixed",
    ],
    changes: [
      "Added RESCHEDULE_ORDER action type with full backend support — AI can propose date changes for approval",
      "Added CRITICAL ACTION RULES to system prompt: AI must use [ACTION] blocks for ALL modifications, never claim 'Done' without one",
      "Added detailed action format documentation to system prompt: RESCHEDULE_ORDER, UPDATE_ORDER, ADD_NOTE, CHANGE_STATUS",
      "Fixed CRITICAL: BOOKED order protection was broken — entity ID lookup failed (used orderId not UUID), so BOOKED orders were never detected and could be modified",
      "Fixed entity ID lookup bug: all action handlers now fall back to orderId lookup when database UUID lookup fails",
      "Fixed CRITICAL: ERTHBOX location lookup was user-scoped — heroes couldn't create ERTHBOX orders from locations created by other users",
      "Fixed: AI chat context only fetched user's own ERTHBOX locations — now fetches all active locations (universal)",
      "Fixed: ERTHBOX locations in AI context now include full ID for use in CREATE_ERTHBOX action blocks",
      "Added audit logging for ADD_NOTE and CHANGE_STATUS actions (was missing)",
      "Added scheduledDate and notes to UPDATE_ORDER allowed fields",
      "RESCHEDULE_ORDER auto-sets status to SCHEDULED if order was PENDING",
      "Improved action regex parser: now uses brace-counting instead of simple regex, handles nested JSON in action payloads",
      "After outputting action blocks, AI now tells user 'Tap ✓ to approve'",
    ],
  },
  {
    version: "v1.9",
    date: "Jun 2026",
    title: "AI Date Accuracy & Timezone Fix",
    highlights: [
      "AI now correctly identifies days of the week — no more wrong day-of-week answers when scheduling",
      "All date/time calculations now use Malaysia Time (UTC+8) properly regardless of server timezone",
      "AI context includes a 14-day reference calendar so it looks up day names instead of calculating",
      "Removed non-functional map feature from Hero dashboard for a cleaner experience",
    ],
    changes: [
      "Fixed critical timezone bug: date helpers (getMalaysiaTime, daysFromNow) now use Asia/Kuala_Lumpur timezone instead of server local time",
      "Fixed getMalaysiaTime() returning wrong time — timeStr was using server local time, not MYT",
      "Fixed daysFromNow() using toISOString() (UTC) which caused date drift when server timezone ≠ UTC+8",
      "Fixed daily-summary route using server-local date formatting instead of Malaysia timezone",
      "Added 14-day reference calendar injected into AI context with day-of-week for each date",
      "AI system prompt now explicitly instructs: 'NEVER calculate days of the week yourself — refer to the reference calendar'",
      "Weekly schedule context now includes day-of-week names (e.g. '📅 2026-06-28 (Sun)')",
      "Current time context now shows day name (e.g. 'Today: 2026-06-14 (Saturday)')",
      "Removed non-functional interactive map from Hero dashboard (OpenStreetMap embed was unreliable)",
      "Updated version display from v1.7 to v1.8",
    ],
  },
  {
    version: "v1.8",
    date: "Jun 2026",
    title: "Universal ERTHBOX & Dashboard Improvements",
    highlights: [
      "ERTHBOX locations are now universal — shared across all heroes, admins, and support users",
      "ERTHBOX location selector now has search and bounded scrolling for easy selection",
      "Removed non-functional map feature from Hero dashboard for a cleaner experience",
    ],
    changes: [
      "ERTHBOX locations are universal: any user can see and use locations created by others",
      "ERTHBOX location selector in New Order has search bar and bounded scroll list (max-h-48)",
      "ERTHBOX Manager shows 'by [name]' badge for locations created by other users",
      "Only the owner, admin, or support can edit/delete ERTHBOX locations",
      "Removed non-functional interactive map from Hero dashboard (OpenStreetMap embed was unreliable)",
      "ErthboxManagerSection search bar appears when 5+ locations exist",
    ],
  },
  {
    version: "v1.7",
    date: "Jun 2026",
    title: "AI Address Verification & Map Updates",
    highlights: [
      "Hero dashboard map now shows all orders with coordinates",
      "Fixed Support user Settings tab visual glitch",
    ],
    changes: [
      "Malaysia bounds validation: coordinates outside Malaysia (0.5-8N, 98-120E) are rejected",
      "AI Address Verification: after Encore import, addresses are auto-verified using DeepSeek LLM",
    ],
  },
  {
    version: "v1.6",
    date: "Jun 2026",
    title: "Role-Based Dashboards & Support Powers",
    highlights: [
      "Three distinct dashboards: Admin (system stats), Support (hero management), Hero (personal workload)",
      "Time range selector (Day/Week/Month/Year/All Time) on all dashboards for granular data",
      "Support users can reassign orders between heroes with notifications and audit logging",
      "Admin dashboard: AI usage, moderation, user activity, order trends, hero workload",
      "Hero dashboard: selectable week workload, interactive order location map, order trends",
      "Support Orders tab: all heroes' orders by default with hero filter & inline reassignment",
    ],
    changes: [
      "Admin Dashboard with system statistics: total orders, AI usage, user activity, audit summary",
      "Admin Dashboard: order creation/deletion/import trends with time-range filtering",
      "Admin Dashboard: user last logins and active users tracking",
      "Admin Dashboard: AI moderation panel with pending flags from dashboard",
      "Admin Dashboard: hero workload comparison with visual bars",
      "Support Dashboard with hero overview: today's workload, weekly points, OFF days",
      "Support Dashboard: selectable week view for hero workload",
      "Support Dashboard: order reassignment panel — move orders between heroes",
      "Support Dashboard: upcoming hero OFF days for the next 2 weeks",
      "Support users can now update and delete any hero's orders (not just their own)",
      "Support users see ALL orders across heroes by default in Orders tab (no toggle needed)",
      "Support users now have access to Settings tab",
      "Reassign orders directly from the Orders tab — click the reassign button on any order card",
      "Order updates/deletions by Support/Admin notify the assigned hero",
      "Filter orders by hero in the Orders tab when viewing all heroes' orders",
      "All reassignments and support actions are logged in audit trail",
      "Hero Dashboard: time range selector (Day/Week/Month/Year/All Time)",
      "Hero Dashboard: selectable week workload with navigation arrows",
      "Hero Dashboard: interactive OpenStreetMap for order locations (with lat/long)",
      "Hero Dashboard: order creation/completion trends mini chart",
      "Hero Dashboard: range stats showing created, completed, and points earned",
      "AI Assistant now provides cross-hero context for Support/Admin users",
      "AI can answer questions like 'Which heroes are working today?' and 'Who has the lightest workload?'",
      "Added lastLoginAt tracking to User model for activity monitoring",
      "Mini bar chart component for order trends visualization",
      "Updated tutorials and onboarding for role-based dashboards",
    ],
  },
  {
    version: "v1.5",
    date: "Jun 2026",
    title: "AI Intelligence Upgrade & Malaysia Timezone",
    highlights: [
      "AI now knows the current date and time in Malaysia Time (UTC+8) — no more wrong dates",
      "Smarter, more contextual answers with order summaries in point form",
      "AI can answer schedule questions like 'Do I have events next week?' and 'Orders in KL next week?'",
      "Increased AI response quality with longer, actionable answers",
      "AI provides daily schedule analysis with points tracking and conflict detection",
    ],
    changes: [
      "Injected dynamic Malaysia Time (MYT, UTC+8) into every AI conversation — AI always knows the current date and time",
      "AI system prompt upgraded to allow longer, substantive answers instead of 2-3 sentence limits",
      "AI can now answer data queries by date range, city, zone, status, and order type",
      "AI provides structured point-form summaries for schedule questions with totals",
      "AI gives actionable insights — not just data, but what the user should do with it",
      "Rich order context injected into AI: today/tomorrow schedule, weekly view, events, ERTHBOX orders, city distribution",
      "AI knows about upcoming holidays, OFF days, and can warn about scheduling conflicts",
      "Increased max_tokens from 512 to 1500 for more detailed responses",
      "Increased temperature from 0.6 to 0.7 for more natural, intelligent answers",
      "AI context now includes full order details: scheduled dates, sizes, points, event types, ERTHBOX locations",
      "AI can calculate daily points and warn when approaching 12pt daily cap",
      "AI provides weekly schedule grouped by date with points per day",
    ],
  },
  {
    version: "v1.4",
    date: "Jun 2026",
    title: "ERTHBOX Management & Event Scheduling System",
    highlights: [
      "ERTHBOX order type for collecting boxes from fixed locations (malls, offices)",
      "ERTHBOX Manager in Settings → Scheduling for managing collection locations",
      "Auto-generated ERTHBOX-XXX order IDs (similar to EVENT-XXX pattern)",
      "Event scheduling system with EVENT-XXX IDs and event day scheduling blocks",
      "Person in Charge (PIC) management per ERTHBOX location",
    ],
    changes: [
      "Added ERTHBOX order type with auto-generated ERTHBOX-001, ERTHBOX-002, etc. IDs",
      "ERTHBOX orders default to PENDING status (manually scheduled, not auto-scheduled)",
      "ERTHBOX Manager section in Settings → Scheduling tab for managing locations",
      "Each ERTHBOX location stores: name, address, city, PIC name, PIC phone, notes",
      "Location info auto-populates when creating ERTHBOX orders",
      "Notes field per location for important info (e.g. 'mall area, cannot enter between 12PM-2PM')",
      "Active/inactive toggle for ERTHBOX locations",
      "ERTHBOX toggle in New Order tab (mutually exclusive with Event toggle)",
      "AI can create ERTHBOX orders via chat with [ACTION:CREATE_ERTHBOX:NEW:{...}]",
      "Event orders with auto-generated EVENT-XXX IDs (EVENT-001, EVENT-002, etc.)",
      "Event types: ROADSHOW, EWASTE_COLLECTION, OTHER",
      "Event days block auto-scheduling — no regular orders auto-assigned on event dates",
      "Auto-scheduler respects event days as OFF days for regular orders",
      "Added Event and ERTHBOX tutorials in Settings → Tutorial",
    ],
  },
  {
    version: "v1.3",
    date: "Jun 2026",
    title: "AI Order Creation, Smart Zones & 2FA Security",
    highlights: [
      "AI can create orders on your behalf — just describe what you need",
      "Smart zone auto-suggestions: AI adds new areas to zones as orders come in",
      "BOOKED orders are now protected — AI won't suggest changes to them",
      "Google Authenticator 2FA for secure sign-in",
      "AI chat integrated into Team Chat with toggle switch",
    ],
    changes: [
      "AI can create orders when prompted — asks for missing info before proceeding",
      "AI auto-detects zones for new orders using address analysis",
      "When a new area is discovered, AI suggests adding it to the nearest zone",
      "Zone suggestions appear in Zone Manager for user approval",
      "BOOKED orders are locked — AI cannot suggest modifications",
      "Added Google Authenticator 2FA (TOTP) for all accounts",
      "2FA setup in Settings → Security with QR code and step-by-step guide",
      "2FA code required at sign-in when enabled",
      "Registration page now shows 2FA security tip",
      "AI chat merged into Team Chat drawer with Team/AI toggle",
      "Mobile-friendly compact AI responses",
      "Updated all version dates to June 2026",
    ],
  },
  {
    version: "v1.2",
    date: "Jun 2026",
    title: "AI Assistant",
    highlights: [
      "ERTH AI Assistant powered by DeepSeek — chat, ask questions, get help",
      "Daily summary and reminder system for Heroes based on order notes",
      "AI can suggest order changes that require user approval before applying",
      "Dangerous or strange requests are automatically flagged for admin review",
      "Admin-only AI settings: API key, model, base URL, system prompt, enable/disable",
    ],
    changes: [
      "Added ERTH AI Assistant with DeepSeek integration (OpenAI-compatible API)",
      "AI answers questions about tutorials, orders, and app features",
      "AI provides zone grouping suggestions based on order patterns",
      "Daily summary with order stats, note reminders, and tomorrow's preview",
      "AI can propose order changes (update, add note, change status) — requires approval",
      "Conversation memory across sessions for contextual follow-ups",
      "Auto-deactivation if API key is invalid or quota is exceeded",
      "Admin can enable/disable AI system-wide",
      "Future-ready: swap API key, base URL, or model for any OpenAI-compatible provider",
      "Flagged messages system for dangerous or inappropriate requests",
      "AI Settings section in Settings tab (admin only)",
      "Floating AI assistant button with chat drawer",
      "Quick prompt buttons: Daily Summary, Order Status, Zone Tips, Tutorial Help",
    ],
  },
  {
    version: "v1.1",
    date: "Jun 2026",
    title: "WhatsApp Messaging Upgrade",
    highlights: [
      "Edit WhatsApp messages before sending to customers",
      "Create and manage message templates with variable placeholders",
      "WhatsApp settings section with phone prefix and template management",
    ],
    changes: [
      "Added WhatsApp message editor dialog — edit messages before sending",
      "Added message template system with create, edit, delete, and set default",
      "4 built-in templates: Schedule Confirmation, Pickup Reminder, Reschedule Notice, Thank You",
      "Template variables: {customerName}, {date}, {address}, {phone}, {orderId}, {size}, {points}, {city}, {notes}",
      "Added WhatsApp settings section in Settings tab",
      "Configurable country code prefix (default: 60 for Malaysia)",
      "Quick variable insert in message editor",
      "WhatsApp button now available for Scheduled, Contacted, Booked, and Completed orders",
      "Added WhatsApp Messaging to advanced tutorials",
      "Updated basic tutorial for WhatsApp usage",
    ],
  },
  {
    version: "v1.0",
    date: "Jun 2026",
    title: "Official Launch",
    highlights: [
      "Complete order management system with full lifecycle tracking",
      "Zone management with custom zones, renaming, and area exclusions",
      "SOS system for order transfers between drivers",
      "Onboarding tutorial and in-app help system",
      "Changelog & version tracking",
    ],
    changes: [
      "Added onboarding walkthrough for first-time users",
      "Added Tutorial & Help section in Settings with Basic and Advanced guides",
      "Added Changelog section to track all app updates",
      "Polished UI with glass-card styling and dark theme",
      "Stabilized all core features for production use",
    ],
  },
  {
    version: "v0.9",
    date: "Jun 2026",
    title: "Tutorial & Help System",
    highlights: [
      "In-app tutorial system with Basic and Advanced tabs",
      "First-sign-in onboarding walkthrough",
      "Replay onboarding from Settings",
    ],
    changes: [
      "Created TutorialSection component with expandable cards",
      "Added onboarding overlay with step-by-step walkthrough",
      "Basic tutorials: Getting Started, Dashboard, Creating Orders, Scheduling, Managing Orders",
      "Advanced tutorials: Zone Management, SOS System, Import & Export, Scheduling Settings, Notifications & Chat, Admin Features",
      "Added 'Replay Onboarding' button in Tutorial section",
    ],
  },
  {
    version: "v0.8",
    date: "Jun 2026",
    title: "Notifications & Team Chat",
    highlights: [
      "Real-time notification system with bell icon",
      "Team chat with @mentions support",
      "Admin message moderation",
    ],
    changes: [
      "Added notification bell with unread badge",
      "System notifications (amber) and normal notifications",
      "Chat panel with @mention autocomplete",
      "Admins can delete inappropriate messages",
      "Notification read/unread tracking",
    ],
  },
  {
    version: "v0.7",
    date: "Jun 2026",
    title: "Zone Customization & User Zones",
    highlights: [
      "Custom zone creation for personalized area grouping",
      "Zone renaming per user account",
      "Area exclusion and restoration",
    ],
    changes: [
      "Users can create custom zones with custom areas",
      "Zone names can be renamed (per-user override)",
      "Areas can be excluded from zones and restored later",
      "Other States zones disabled by default with enable toggle",
      "Zone Map UI with collapsible regions",
    ],
  },
  {
    version: "v0.6",
    date: "Jun 2026",
    title: "Self-Registration & User Approval",
    highlights: [
      "Self-registration from login page",
      "Admin approval workflow for new accounts",
      "Improved user management",
    ],
    changes: [
      "New users can register with username, password, and display name",
      "Unapproved users cannot sign in until admin approves",
      "Users tab shows pending registrations with approve/reject actions",
      "Fixed isApproved default for existing users",
      "Added audit logging for user management actions",
    ],
  },
  {
    version: "v0.5",
    date: "Jun 2026",
    title: "Role-Based Access Control (RBAC)",
    highlights: [
      "Three user roles: ADMIN, HERO, SUPPORT",
      "Permission-based feature access",
      "Admin-only settings and user management",
    ],
    changes: [
      "ADMIN: Full access to all features, user management, audit logs",
      "HERO: Order management, scheduling, SOS, personal settings",
      "SUPPORT: Order viewing, SOS answering, chat, limited settings",
      "Role badges with color coding in user list",
      "Protected API endpoints with role checks",
    ],
  },
  {
    version: "v0.4",
    date: "Jun 2026",
    title: "SOS System & Audit Logging",
    highlights: [
      "SOS requests for order transfers between drivers",
      "Admin/Support can assign SOS to specific heroes",
      "Comprehensive audit trail",
    ],
    changes: [
      "HERO users can send SOS for orders they can't handle",
      "SOS tab shows all active requests",
      "Admin/Support can assign SOS to specific heroes instead of answering directly",
      "Audit log tracks all significant actions (order changes, user events, SOS)",
      "Filterable audit log in Settings",
    ],
  },
  {
    version: "v0.3",
    date: "Jan 2025",
    title: "Scheduling & Calendar",
    highlights: [
      "Auto-scheduling with daily capacity limits",
      "Visual calendar with color-coded load indicators",
      "Weekend and holiday restrictions",
    ],
    changes: [
      "Auto-schedule distributes pending orders across available days",
      "12-point daily capacity (S=1pt, M=2pt, L=3pt)",
      "Monthly calendar view with green/amber/red day indicators",
      "Office pickups excluded from weekends and public holidays",
      "OFF days block all scheduling",
      "Weekly load bar chart visualization",
      "Manual rescheduling with mini calendar picker",
    ],
  },
  {
    version: "v0.2",
    date: "Jan 2025",
    title: "Import & Export Integrations",
    highlights: [
      "Encore CSV import for bulk order creation",
      "Zeo Route Planner XLSX export",
      "Google Sheets sync (bidirectional)",
    ],
    changes: [
      "Import orders from Encore CSV exports",
      "Auto-detect city/area and assign zones during import",
      "Duplicate detection by Order ID",
      "Export scheduled/contacted orders as XLSX for Zeo Route Planner",
      "Google Sheets integration with push/pull sync",
      "CSV template download for Encore format",
    ],
  },
  {
    version: "v0.1",
    date: "Dec 2024",
    title: "Initial Release — Core Foundation",
    highlights: [
      "Order creation and management",
      "Zone-based area detection for Selangor & KL",
      "Status workflow: Pending → Scheduled → Contacted → Booked → Completed",
    ],
    changes: [
      "Create individual orders with customer details, address, size, and zone",
      "Auto zone detection based on city/area input",
      "14 built-in zones covering Selangor/KL and Other States",
      "Order status management with full lifecycle tracking",
      "WhatsApp integration for customer notifications",
      "Dashboard with status overview cards",
      "Points system: S=1pt, M=2pt, L=3pt",
      "Authentication with NextAuth.js (credentials provider)",
      "Dark theme with glass-card UI design",
    ],
  },
] as const;
